//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ScannerSDKSampleApp.rc
//
#define IDD_Miscellaneous               1
#define IDD_SCANNERSDKSAMPLEAPP_DIALOG  102
#define IDR_MAINFRAME                   128
#define IDD_ScannerActions              129
#define IDD_XML                         130
#define IDD_Barcode                     131
#define IDD_ImageVideo                  132
#define IDD_RSM                         133
#define IDD_Configuration               134
#define IDD_Advanced                    135
#define IDD_Logs                        136
#define IDD_DIALOG1                     141
#define IDD_TOPOLOGY                    141
#define IDD_Scale                       143
#define IDD_DIALOG2                     144
#define IDD_IntelDocCap                 144
#define IDD_TOPOLOGY1                   145
#define IDD_DadfScript                  146
#define IDD_ScanToConnect               148
#define IDC_TAB1                        1000
#define IDC_BUTTON1                     1001
#define IDC_BUTTON2                     1002
#define IDC_EDIT1                       1003
#define IDC_BUTTON11                    1003
#define IDC_BUTTON3                     1004
#define IDC_BUTTON14                    1004
#define IDC_LIST1                       1005
#define IDC_BUTTON13                    1005
#define IDC_BUTTON15                    1005
#define IDC_CHECK1                      1006
#define IDC_CHECK2                      1007
#define IDC_CHECK3                      1008
#define IDC_CHECK4                      1009
#define IDC_CHECK5                      1010
#define IDC_CHECK6                      1011
#define IDC_CHECK7                      1012
#define IDC_CHECK8                      1013
#define IDC_CHECK9                      1014
#define IDC_CHECK10                     1015
#define IDC_CHECK11                     1016
#define IDC_CHECK12                     1017
#define IDC_CHECK13                     1018
#define IDC_CHECK14                     1019
#define IDC_BUTTON4                     1020
#define IDC_BUTTON5                     1021
#define IDC_CHECK15                     1022
#define IDC_BUTTON12                    1022
#define IDC_CHECK16                     1023
#define IDC_BUTTON6                     1024
#define IDC_BUTTON7                     1025
#define IDC_EDIT2                       1026
#define IDC_BUTTON9                     1026
#define IDC_COMBO1                      1027
#define IDC_BUTTON10                    1027
#define IDC_EDIT3                       1027
#define IDC_ANIMATE1                    1028
#define IDC_CHECK17                     1028
#define IDC_COMBO3                      1028
#define IDC_EDIT9                       1028
#define IDC_EDIT_Attrib                 1029
#define IDC_CHECK18                     1029
#define IDC_TREE1                       1030
#define IDC_BUTTON8                     1031
#define IDC_BUTTON_DISABLE              1031
#define IDC_PROGRESS1                   1032
#define IDC_LIST2                       1033
#define IDC_RADIO1                      1034
#define IDC_RADIO2                      1035
#define IDC_RADIO3                      1036
#define IDC_EDIT4                       1037
#define IDC_EDIT_IDC_SYMBOLOGY          1037
#define IDC_EDIT_Barcode                1037
#define IDC_EDIT5                       1038
#define IDC_EDIT6                       1039
#define IDC_EDIT7                       1040
#define IDC_EDIT8                       1041
#define IDC_EXPLORER1                   1042
#define IDC_STATIC_PICTURE_CONTROL      1043
#define IDC_COMBO_HOSTS                 1044
#define IDC_COMBO2                      1045
#define IDC_COMBO4                      1046
#define IDC_ENABLELANG                  1046
#define IDC_CMBLANG                     1047
#define IDC_BUTTON_ReadWeight           1048
#define IDC_ENABLELANG2                 1048
#define IDC_DRIVERADF                   1048
#define IDC_BUTTON_ZeroScale            1049
#define IDC_BUTTON_ScaleReset           1050
#define IDC_STATIC_WeightValue          1051
#define IDC_STATIC_WeightUnit           1052
#define IDC_STATIC_ScaleStatus          1053
#define IDC_STATIC_IDC_PIC_CTRL         1054
#define IDC_COMBO_IDC_PARAM             1055
#define IDC_EDIT_IDC_PARAM_VAL          1056
#define IDC_BUTTON_IDC_PARAM_GET        1057
#define IDC_BUTTON_IDC_PARAM_SET        1058
#define IDC_BUTTON_IDC_PARAM_STORE      1059
#define IDC_EDITI_IDC_DECODE_DATA       1060
#define IDC_BUTTON_IDC_CLEAR            1061
#define IDC_CHECK_USE_HID               1062
#define IDC_BUTTON_DecodeToneBrrowse    1063
#define IDC_RICHEDIT21                  1063
#define IDC_BUTTON_DecodeToneUpload     1064
#define IDC_EDIT_Logs                   1064
#define IDC_BUTTON_DecodeToneErase      1065
#define IDC_COMBO_ScannerType           1065
#define IDC_EDIT_DecodeToneFilePath     1066
#define IDC_STATIC_ScannerType          1066
#define IDC_STATIC_ProtocolName         1067
#define IDC_EDIT_ElectricFenceCustomTonePath 1067
#define IDC_STATIC_HostName             1068
#define IDC_BUTTON_ElectricFenceCustomToneBrowse 1068
#define IDC_STATIC_DefaultOption        1069
#define IDC_BUTTON_ElectricFenceCustomToneUpload 1069
#define IDC_STATIC_ImageSize            1070
#define IDC_BUTTON_ElectricFenceCustomToneErase 1070
#define IDC_STATIC_BMPPath              1071
#define IDC_STATIC_ScanToConnectBarcodeGroup 1072
#define IDC_COMBO5                      1073
#define IDC_COMBO_ImageSize             1073
#define IDC_STATIC_ScanToConnectBarcode 1074
#define IDC_COMBO_ProtocolName          1075
#define IDC_COMBO_HostName              1076
#define IDC_COMBO_DefaultOption         1077
#define IDC_STATIC_PairingBarcode       1078
#define IDC_BUTTON_Disconnect           1079
#define IDC_BUTTON_Brows                1083
#define IDC_BUTTON_SaveBarcode          1085
#define IDC_SAVE_IMAGE                  1086
#define IDC_BUTTON_IDC_SAVE_IMAGE       1086
#define IDC_BUTTON_ENABLE               1087

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        154
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1088
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
